apiVersion: v1
kind: Service
metadata:
  name: gate
spec:
  selector:
    app.kubernetes.io/component: proxy
  type: NodePort
  ports:
  - port: 25565
    targetPort: minecraft
    protocol: TCP
    name: minecraft
    nodePort: 32556
